import { Box, Button, Grid, Paper, TextField, Typography } from '@mui/material';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useForm, Controller, SubmitHandler } from 'react-hook-form';

type PinFormInput = {
    pin?: number | string;
};

export default function Home() {
    const router = useRouter();
    const {
        control,
        handleSubmit,
        setError,
        formState: { errors },
    } = useForm<PinFormInput>();

    const onSubmit: SubmitHandler<PinFormInput> = async (data) => {
        // calling the API route I setup to get the account info
        const response = await fetch('/api/customer', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ pin: data.pin }),
        });

        const { result } = await response.json();

        // redirects to the ATM page
        if (result) {
            await router.push({
                pathname: '/atm',
                // very simplistic way of getting the data to the page
                // normally I would have used some kind of cookie auth
                query: {
                    firstName: result.firstName,
                    lastName: result.lastName,
                    account: result.account,
                },
            });
        }

        // sets the error message if the account cannot be found
        setError(
            'pin',
            { type: 'custom', message: 'Unable to find account' },
            { shouldFocus: true }
        );
    };

    return (
        <>
            <Head>
                <title>Basic ATM - Pin entry</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Box maxWidth="md" sx={{ margin: 'auto' }}>
                    <Paper sx={{ padding: '2em' }}>
                        <Grid container spacing={2}>
                            <Grid item xs={12} sx={{ textAlign: 'center' }}>
                                <Typography variant="h2">Basic ATM</Typography>
                            </Grid>
                            <Grid item xs={12}>
                                <Grid container sx={{ textAlign: 'center' }}>
                                    <Grid item xs={12}>
                                        <Typography variant="h5" component="p">
                                            Enter your pin number:
                                        </Typography>
                                    </Grid>
                                    <Grid item xs={12}>
                                        <form onSubmit={handleSubmit(onSubmit)}>
                                            <Controller
                                                name="pin"
                                                control={control}
                                                rules={{
                                                    required: true,
                                                    minLength: 4,
                                                    maxLength: 4,
                                                }}
                                                render={({ field }) => (
                                                    <TextField
                                                        InputLabelProps={{
                                                            shrink: true,
                                                        }}
                                                        InputProps={{
                                                            endAdornment: (
                                                                <Button
                                                                    type="submit"
                                                                    variant="contained"
                                                                >
                                                                    Submit
                                                                </Button>
                                                            ),
                                                        }}
                                                        error={!!errors.pin}
                                                        helperText={
                                                            errors?.pin?.message
                                                        }
                                                        {...field}
                                                    />
                                                )}
                                                defaultValue={undefined}
                                            />
                                        </form>
                                    </Grid>
                                </Grid>
                            </Grid>
                        </Grid>
                    </Paper>
                </Box>
            </main>
        </>
    );
}
